Hymnal App Database one-time setups
Church-Life-Apps/Backend pull request #15
Opened 2023-01-28 04:13 UTC by brandonxia01

Set up some stuff for database layer code and created Database table queries which only need to be run once (but are idempotent)

2023-01-28 22:58 UTC, brotatotes reviewed
Overall this looks awesome. I left some relevant comments/questions in the design doc, so I won't duplicate them here.

2023-01-29 03:35 UTC, brotatotes requested changes

2023-01-29 03:35 UTC, brotatotes commented on src/db/DbModels.tsx
> +  presentationOrder: number;
I think can be moved to DbSong

2023-01-29 03:35 UTC, brotatotes commented on src/db/DbModels.tsx
> +  presentationOrder: number;
I think can be moved to DbSong

2023-01-29 03:44 UTC, brandonxia01 commented on src/db/DbModels.tsx
> +  presentationOrder: number;
done. dbs updated as well

2023-01-29 03:49 UTC, brotatotes approved these changes
epic!!!

2023-01-29 03:52 UTC, merged