Add GetSong With Lyrics API
Church-Life-Apps/Backend pull request #18
Opened 2023-02-21 03:17 UTC by brandonxia01

Add get songs with lyrics API. 

<img width="1429" alt="Screen Shot 2023-02-20 at 10 12 04 PM" src="https://user-images.githubusercontent.com/8559293/220238788-e741c6e1-7409-4e19-9440-64493accd2d2.png">

2023-02-21 03:19 UTC, brandonxia01 commented on src/test/utils/StringUtils.test.ts
> +// test('Tests IsNumeric', () => {
Test cases will come soon... I tried for like 20mins to set up Jest but I don't know how. May need help.

2023-02-22 23:26 UTC, MiTo0o requested changes

2023-02-22 23:26 UTC, MiTo0o commented on src/index.ts
> +    res.status(200).send(await songsService.getSongsMethod(songbookId));
for all of the `res.status(200).send()` you can just write `res.send()` because status code 200 is the default.

2023-02-23 00:28 UTC, brandonxia01 commented on src/index.ts
>  });
Will do!

2023-02-23 00:28 UTC, brandonxia01 commented on src/index.ts
> +    res.status(200).send(await songsService.getSongsMethod(songbookId));
Cool

2023-02-23 00:28 UTC, brandonxia01 commented on src/services/SongsService.ts
> +    const songsDb = new SongsDb(null);
Good catch!

2023-02-23 01:55 UTC, MiTo0o approved these changes
lgtm

2023-02-23 02:00 UTC, merged